# Generated by Django 5.2 on 2026-03-05 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('value', models.TextField(blank=True)),
                ('is_secret', models.BooleanField(default=False, help_text='Encrypt data at rest and hide it from unauthorized reads.')),
            ],
        ),
    ]
