# Generated by Django 5.2 on 2026-03-04 12:48

from django.db import migrations, models
from django.utils.text import slugify


def fill_board_slugs(apps, schema_editor):
    """Historical models skip Board.save(), so slugify here. `-<pk>` breaks ties; 50 = the field's max_length."""
    Board = apps.get_model('boards', 'Board')
    taken = set()
    for board in Board.objects.order_by('pk'):
        slug = slugify(board.name)[:50] or f'board-{board.pk}'
        if slug in taken:
            slug = f'{slugify(board.name)[:50 - len(str(board.pk)) - 1]}-{board.pk}'
        taken.add(slug)
        board.slug = slug
        board.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_remove_topic_last_update_topic_last_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['-is_pinned', '-last_updated']},
        ),
        migrations.AddField(
            model_name='board',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        # Nullable and unindexed first: adding a unique column fills every existing row with '' and collides
        # at two boards. The AlterField below adds the unique index (and its _like twin) once.
        migrations.AddField(
            model_name='board',
            name='slug',
            field=models.SlugField(blank=True, null=True, db_index=False),
        ),
        migrations.RunPython(fill_board_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='board',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topic',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topic',
            name='slug',
            field=models.SlugField(blank=True, max_length=280),
        ),
        migrations.AddField(
            model_name='topic',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
