# Generated by Django 5.2 on 2026-09-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_reaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
