# Generated by Django 5.2 on 2026-09-18 06:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_topic_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['topic', 'created_at'], name='boards_post_topic_i_0bf412_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['board', '-is_pinned', '-last_updated'], name='boards_topi_board_i_c14d44_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['-views_count', '-last_updated'], name='boards_topi_views_c_78d7cd_idx'),
        ),
    ]
